name: Unit Test
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn jest
